#!/bin/bash
#    rcat 
#    Copyright (C) 2011  Satish Eerpini
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#script to remotely concatenate files.
#args -> rcat file1 file2 
#concatenates file1 to remote file file2
local_file=$1
username=`echo $2 | sed 's/:/\t/g' | awk '{print $1}' | sed 's/@/\t/g' | awk '{print $1}'`
remote_host=`echo $2 | sed 's/:/\t/g' | awk '{print $1}' | sed 's/@/\t/g' | awk '{print $2}'`
remote_file=`echo $2 | sed 's/:/\t/g' | awk '{print $2}'`
temp_folder="/tmp/$#"
file_name=`echo $local_file  | sed 's/\// /g' | awk '{print $NF}'`
if [ -d $local_file ] ;
then
	echo "Cannot cat a directory"
	echo "Qutting"
	exit
fi
rsync $local_file $username@$remote_host:$temp_folder/
ssh $username@$remote_host "cat $temp_folder/$file_name >> $remote_file && rm -rf $temp_folder/$file_name"
echo "done"
echo "rcat $local_file $username@$remote_host:$remote_file"

