#!/bin/bash
#    sync_code 
#    Copyright (C) 2011  Satish Eerpini
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

rsync -av ~/progr/dsitributed_systems/flume node1:/home/satish/progr/distributed_systems/
rsync -av ~/progr/dsitributed_systems/flume node2:/home/satish/progr/distributed_systems/
rsync -av ~/progr/dsitributed_systems/flume 192.168.122.116:/home/satish/progr/distributed_systems/
