#!/bin/bash
#    vm_starter 
#    Copyright (C) 2011  Satish Eerpini
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.


echo -ne $"Enter the name of the virtual machine\n"
read vm

sudo virsh start $vm
var_ssh=`echo "ssh $USER@$vm"`
tmux previous-window
#sleep 20
echo -ne "\rTrying to connect to $vm"
tmux new-window -n "$vm" "$var_ssh"
tmux select-window -n "$vm"
while ! [ $? -eq 0 ]
do
	sleep 4
	echo -ne "\rFailed connecting, Trying to reconnect to $vm"
	tmux new-window -n "$vm" "$var_ssh"
	tmux select-window -t "0:$vm"
done

#tmux select-window -t "$vm"
